"""
CodeSentinel — Step 6Q-D: GitHub PR Security Commenter

Formats and posts/updates deterministic Markdown security analysis comments on GitHub Pull Requests.
Prevents duplicate comments by identifying the stable marker `<!-- codesentinel-security-analysis -->`.
"""

from typing import Any, Dict, Optional

try:
    from backend.github.client import GitHubClient
    from backend.github.validator import (
        validate_webhook_owner,
        validate_webhook_repo,
        validate_pr_number
    )
except ImportError:
    from github.client import GitHubClient
    from github.validator import (
        validate_webhook_owner,
        validate_webhook_repo,
        validate_pr_number
    )


COMMENT_MARKER = "<!-- codesentinel-security-analysis -->"

DECISION_TO_COMMENT_LABEL = {
    "allow": "PASSED / Safe to Merge",
    "block": "BLOCKED / Do Not Merge",
    "review": "REVIEW NEEDED / Manual Review Required"
}

DECISION_TO_NEXT_ACTION = {
    "allow": "No blocking security vulnerabilities detected. Code is safe to merge.",
    "block": "High or critical severity security vulnerabilities were detected. Remediate findings before merging.",
    "review": "Security findings require manual review by a security reviewer before proceeding."
}


def format_pr_security_comment(
    report: Dict[str, Any],
    owner: str = "",
    repository: str = "",
    pr_number: Optional[int] = None
) -> str:
    """
    Transforms a Step 6O Production Report into a deterministic Markdown PR security comment.

    Args:
        report: Valid Step 6O Production Report dictionary.
        owner: Optional repository owner name.
        repository: Optional repository name.
        pr_number: Optional PR number.

    Returns:
        Formatted Markdown string containing the COMMENT_MARKER.
    """
    if not isinstance(report, dict):
        raise ValueError("Step 6O report must be a non-empty dictionary")

    review_status = str(report.get("review_status", "allow")).lower()
    decision_label = DECISION_TO_COMMENT_LABEL.get(review_status, "PASSED / Safe to Merge")
    next_action = DECISION_TO_NEXT_ACTION.get(review_status, "Review security findings before merging.")

    summary = report.get("summary", {}) if isinstance(report.get("summary"), dict) else {}
    crit_count = int(summary.get("critical_count", 0))
    high_count = int(summary.get("high_count", 0))
    med_count = int(summary.get("medium_count", 0))
    low_count = int(summary.get("low_count", 0))
    info_count = int(summary.get("info_count", 0))
    total_findings = int(summary.get("total_findings", len(report.get("findings", []))))
    analyzed_files = int(summary.get("analyzed_files", 0))

    repo_info = ""
    if owner and repository:
        repo_info = f" for **{owner}/{repository}**"
        if pr_number:
            repo_info += f" (PR #{pr_number})"

    markdown = (
        f"{COMMENT_MARKER}\n"
        f"## CodeSentinel Security Analysis{repo_info}\n\n"
        f"**Security Gate Verdict**: `{decision_label}`\n\n"
        f"### Summary Telemetry\n"
        f"- **Analyzed Files**: {analyzed_files}\n"
        f"- **Total Security Findings**: {total_findings}\n"
        f"- **Critical Severity**: `{crit_count}`\n"
        f"- **High Severity**: `{high_count}`\n"
        f"- **Medium Severity**: `{med_count}`\n"
        f"- **Low Severity**: `{low_count}`\n"
        f"- **Info**: `{info_count}`\n\n"
    )

    findings = report.get("findings", [])
    if findings and isinstance(findings, list):
        markdown += "### Key Findings\n\n"
        for idx, f in enumerate(findings[:10], start=1):
            if isinstance(f, dict):
                f_id = f.get("finding_id", f"finding_{idx}")
                f_title = str(f.get("title", "Security Finding")).strip()
                f_sev = str(f.get("severity", "unknown")).upper()
                markdown += f"{idx}. **[{f_sev}]** `{f_id}` — {f_title}\n"
        if len(findings) > 10:
            markdown += f"\n*...and {len(findings) - 10} additional findings.*"
        markdown += "\n\n"

    markdown += (
        f"### Recommended Next Action\n"
        f"{next_action}\n\n"
        f"---  \n"
        f"*Automated DevSecOps Security Audit generated by CodeSentinel Security OS.*"
    )

    return markdown


def post_pr_security_comment(
    owner: str,
    repository: str,
    pr_number: int,
    report: Dict[str, Any],
    client: Optional[GitHubClient] = None
) -> Dict[str, Any]:
    """
    Posts or updates a GitHub Pull Request security comment.
    Searches for an existing comment with `COMMENT_MARKER` and updates it if present.

    Args:
        owner: Repository owner.
        repository: Repository name.
        pr_number: PR number.
        report: Step 6O Production Report dictionary.
        client: Optional GitHubClient instance.

    Returns:
        GitHub API response dictionary for comment creation/update.
    """
    clean_owner = validate_webhook_owner(owner)
    clean_repo = validate_webhook_repo(repository)
    clean_pr_num = validate_pr_number(pr_number)

    api_client = client or GitHubClient()
    comment_body = format_pr_security_comment(report, owner=clean_owner, repository=clean_repo, pr_number=clean_pr_num)

    # 1. Search for existing comments on the PR/issue
    list_endpoint = f"/repos/{clean_owner}/{clean_repo}/issues/{clean_pr_num}/comments"
    comments_res = api_client.get(list_endpoint)

    existing_comment_id = None
    if isinstance(comments_res, list):
        for c in comments_res:
            if isinstance(c, dict) and COMMENT_MARKER in str(c.get("body", "")):
                existing_comment_id = c.get("id")
                break

    # 2. Update existing comment or post new comment
    if existing_comment_id:
        update_endpoint = f"/repos/{clean_owner}/{clean_repo}/issues/comments/{existing_comment_id}"
        return api_client.request("PATCH", update_endpoint, json_data={"body": comment_body})
    else:
        post_endpoint = f"/repos/{clean_owner}/{clean_repo}/issues/{clean_pr_num}/comments"
        return api_client.request("POST", post_endpoint, json_data={"body": comment_body})
