"""
CodeSentinel — Step 6R-D: CI/CD Security Reporting & PR Integration

Formats Step 6O Production Security Reports into safe, deterministic Markdown summaries
for GitHub Actions ($GITHUB_STEP_SUMMARY) and GitHub Pull Requests while preserving the
6Q comment marker ('<!-- codesentinel-security-analysis -->').
"""

import json
import os
import sys
from typing import Any, Dict, Optional

COMMENT_MARKER = "<!-- codesentinel-security-analysis -->"

DECISION_LABEL_MAP = {
    "allow": "ALLOW / Safe to Merge",
    "review": "REVIEW / Manual Review Required",
    "block": "BLOCK / Do Not Merge"
}

RECOMMENDATION_MAP = {
    "allow": "Safe to merge. No critical, high, or medium security vulnerabilities were detected.",
    "review": "Manual security review required. Medium severity findings require security review before merging.",
    "block": "Do not merge. High or critical severity security findings were detected. Remediate findings before merging."
}


def generate_ci_security_summary(
    report: Dict[str, Any],
    repository_ref: Optional[str] = None,
    branch_ref: Optional[str] = None
) -> str:
    """
    Transforms a Step 6O Production Report into safe Markdown suitable for
    GitHub Actions $GITHUB_STEP_SUMMARY and GitHub PR comments.

    Args:
        report: Valid Step 6O Production Security Report dictionary.
        repository_ref: Optional custom repository name string (e.g. owner/repo).
        branch_ref: Optional branch name string.

    Returns:
        Formatted Markdown string containing the COMMENT_MARKER.

    Raises:
        ValueError: If report is not a valid dictionary or lacks required fields.
    """
    if not isinstance(report, dict):
        raise ValueError("Security report must be a non-empty dictionary")

    status = str(report.get("status", "failed")).lower()
    if status not in ("success", "completed"):
        raise ValueError(f"Cannot generate security summary for failed or invalid analysis status: {status}")

    review_status = str(report.get("review_status", "allow")).lower()

    analysis_id = str(report.get("analysis_id", "N/A"))

    # Extract repository metadata
    raw_repo = report.get("repository") if isinstance(report.get("repository"), dict) else {}
    owner = str(raw_repo.get("owner", ""))
    repo_name = str(raw_repo.get("repository", ""))
    branch = branch_ref or str(raw_repo.get("branch", "main"))

    repo_str = repository_ref or (f"{owner}/{repo_name}" if owner and repo_name else repo_name or "Target Repository")

    # Extract severity summary
    summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
    crit_count = int(summary.get("critical_count", 0))
    high_count = int(summary.get("high_count", 0))
    med_count = int(summary.get("medium_count", 0))
    low_count = int(summary.get("low_count", 0))
    info_count = int(summary.get("info_count", 0))
    total_findings = int(summary.get("total_findings", len(report.get("findings", []))))

    decision_text = DECISION_LABEL_MAP.get(review_status, "ALLOW / Safe to Merge")
    recommendation = RECOMMENDATION_MAP.get(review_status, "Review security findings before merging.")

    markdown_parts = [
        COMMENT_MARKER,
        "## CodeSentinel Security Analysis",
        f"- **Repository**: `{repo_str}`",
        f"- **Branch**: `{branch}`",
        f"- **Analysis ID**: `{analysis_id}`",
        "",
        f"### Security Decision: `{decision_text}`",
        "",
        "### Severity Summary",
        f"- **Total Findings**: `{total_findings}`",
        f"- **Critical**: `{crit_count}`",
        f"- **High**: `{high_count}`",
        f"- **Medium**: `{med_count}`",
        f"- **Low**: `{low_count}`",
        f"- **Info**: `{info_count}`",
        "",
        "### Recommended Action",
        f"{recommendation}",
        ""
    ]

    # Include sanitized finding titles (up to 10)
    findings = report.get("findings", [])
    if isinstance(findings, list) and findings:
        markdown_parts.append("### Key Security Findings")
        for idx, f in enumerate(findings[:10], start=1):
            if isinstance(f, dict):
                f_id = str(f.get("finding_id") or f"finding_{idx}")
                f_title = str(f.get("title") or "Security Finding").strip()
                f_sev = str(f.get("severity") or "unknown").upper()
                markdown_parts.append(f"{idx}. **[{f_sev}]** `{f_id}` — {f_title}")
        if len(findings) > 10:
            markdown_parts.append(f"\n*...and {len(findings) - 10} additional findings.*")
        markdown_parts.append("")

    markdown_parts.append("---")
    markdown_parts.append("*Automated DevSecOps Security Audit generated by CodeSentinel.*")

    return "\n".join(markdown_parts)


def write_github_step_summary(report_path: str) -> bool:
    """
    Reads report from report_path, generates Markdown summary, and appends to $GITHUB_STEP_SUMMARY if set.
    """
    if not report_path or not os.path.exists(report_path):
        return False

    try:
        with open(report_path, "r", encoding="utf-8") as f:
            report = json.load(f)

        summary_md = generate_ci_security_summary(report)

        step_summary_file = os.environ.get("GITHUB_STEP_SUMMARY")
        if step_summary_file:
            with open(step_summary_file, "a", encoding="utf-8") as sf:
                sf.write(summary_md + "\n")

        print(summary_md)
        return True
    except Exception as e:
        print(f"Error generating CI security summary: {e}", file=sys.stderr)
        return False


def main() -> int:
    """CLI entry point for generating CI security report summary."""
    import argparse

    parser = argparse.ArgumentParser(description="CodeSentinel CI Security Report Formatter")
    parser.add_argument(
        "--report",
        default="security-report.json",
        help="Path to Step 6O security report JSON file"
    )
    parser.add_argument(
        "--append-step-summary",
        action="store_true",
        help="Append formatted Markdown summary to GITHUB_STEP_SUMMARY environment file"
    )

    args = parser.parse_args()
    success = write_github_step_summary(args.report)
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
